package sys.model;
// Generated 3/10/2018 12:48:46 PM by Hibernate Tools 4.3.1



/**
 * Alerta generated by hbm2java
 */
public class Alerta  implements java.io.Serializable {


     private int idAlerta;
     private String mensaje;

    public Alerta() {
    }

    public Alerta(int idAlerta, String mensaje) {
       this.idAlerta = idAlerta;
       this.mensaje = mensaje;
    }
   
    public int getIdAlerta() {
        return this.idAlerta;
    }
    
    public void setIdAlerta(int idAlerta) {
        this.idAlerta = idAlerta;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }




}


