package sys.model;
// Generated 3/10/2018 12:48:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Historico generated by hbm2java
 */
public class Historico  implements java.io.Serializable {


     private int idHistorico;
     private Solicitud idSolicitud;
     private Estado idEstado;
     private Date fechaActualizacion;
     private String observacion;
     private Usuario idUsuario;

    public Historico() {
    }

	
    public Historico(int idHistorico, Solicitud idSolicitud, Estado idEstado, Date fechaActualizacion, Usuario idUsuario) {
        this.idHistorico = idHistorico;
        this.idSolicitud = idSolicitud;
        this.idEstado = idEstado;
        this.fechaActualizacion = fechaActualizacion;
        this.idUsuario = idUsuario;
    }
    public Historico(int idHistorico, Solicitud idSolicitud, Estado idEstado, Date fechaActualizacion, String observacion, Usuario idUsuario) {
       this.idHistorico = idHistorico;
       this.idSolicitud = idSolicitud;
       this.idEstado = idEstado;
       this.fechaActualizacion = fechaActualizacion;
       this.observacion = observacion;
       this.idUsuario = idUsuario;
    }
   
    public int getIdHistorico() {
        return this.idHistorico;
    }
    
    public void setIdHistorico(int idHistorico) {
        this.idHistorico = idHistorico;
    }
    public Solicitud getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Solicitud idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Estado getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Estado idEstado) {
        this.idEstado = idEstado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Usuario getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Usuario idUsuario) {
        this.idUsuario = idUsuario;
    }




}


