package sys.model;
// Generated 3/10/2018 12:48:46 PM by Hibernate Tools 4.3.1



/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private int idPerfil;
     private String perfil;

    public Perfil() {
    }

    public Perfil(int idPerfil, String perfil) {
       this.idPerfil = idPerfil;
       this.perfil = perfil;
    }
   
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }




}


