package sys.model;
// Generated 3/10/2018 12:48:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private int idSolicitud;
     private Usuario idUsuario;
     private Date fechaCreacion;
     private Estado idEstadoActual;
     private Boolean esPrioridad;
     private Boolean esAtipico;
     private String observacionAtipico;
     private String observacionPrioridad;
     private String nombreContacto;
     private String cargoContacto;
     private String correoContacto;
     private String direccionCliente;
     private String celularTelefono;
     private String ciudadDepartamento;
     private String numeroCotizacion;
     private String razonSocial;
     private int tiempoDiaAtipico;
     private int tiempoHoraAtipico;
     private int tiempoMinutoAtipico;
     private int tiempoDiaOferta;
     private int tiempoHoraOferta;
     private int tiempoMinutoOferta;
     private Usuario idProfesionalAsignado;
     private TipoCertificacion idTipoCertificacion;

    public Solicitud() {
    }

	
    public Solicitud(int idSolicitud, Usuario idUsuario, Date fechaCreacion, Estado idEstadoActual) {
        this.idSolicitud = idSolicitud;
        this.idUsuario = idUsuario;
        this.fechaCreacion = fechaCreacion;
        this.idEstadoActual = idEstadoActual;
    }

    public Solicitud(int idSolicitud, Usuario idUsuario, Date fechaCreacion, Estado idEstadoActual, Boolean esPrioridad, Boolean esAtipico, String observacionAtipico, String observacionPrioridad, String nombreContacto, String cargoContacto, String correoContacto, String direccionCliente, String celularTelefono, String ciudadDepartamento, String numeroCotizacion, String razonSocial, int tiempoDiaAtipico, int tiempoHoraAtipico, int tiempoMinutoAtipico, int tiempoDiaOferta, int tiempoHoraOferta, int tiempoMinutoOferta, Usuario idProfesionalAsignado, TipoCertificacion idTipoCertificacion) {
        this.idSolicitud = idSolicitud;
        this.idUsuario = idUsuario;
        this.fechaCreacion = fechaCreacion;
        this.idEstadoActual = idEstadoActual;
        this.esPrioridad = esPrioridad;
        this.esAtipico = esAtipico;
        this.observacionAtipico = observacionAtipico;
        this.observacionPrioridad = observacionPrioridad;
        this.nombreContacto = nombreContacto;
        this.cargoContacto = cargoContacto;
        this.correoContacto = correoContacto;
        this.direccionCliente = direccionCliente;
        this.celularTelefono = celularTelefono;
        this.ciudadDepartamento = ciudadDepartamento;
        this.numeroCotizacion = numeroCotizacion;
        this.razonSocial = razonSocial;
        this.tiempoDiaAtipico = tiempoDiaAtipico;
        this.tiempoHoraAtipico = tiempoHoraAtipico;
        this.tiempoMinutoAtipico = tiempoMinutoAtipico;
        this.tiempoDiaOferta = tiempoDiaOferta;
        this.tiempoHoraOferta = tiempoHoraOferta;
        this.tiempoMinutoOferta = tiempoMinutoOferta;
        this.idProfesionalAsignado = idProfesionalAsignado;
        this.idTipoCertificacion = idTipoCertificacion;
    }


    

   
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Usuario getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Usuario idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Estado getIdEstadoActual() {
        return this.idEstadoActual;
    }
    
    public void setIdEstadoActual(Estado idEstadoActual) {
        this.idEstadoActual = idEstadoActual;
    }

    public Boolean getEsPrioridad() {
        return this.esPrioridad;
    }
    
    public void setEsPrioridad(Boolean esPrioridad) {
        this.esPrioridad = esPrioridad;
    }
    public Boolean getEsAtipico() {
        return this.esAtipico;
    }
    
    public void setEsAtipico(Boolean esAtipico) {
        this.esAtipico = esAtipico;
    }

    public String getObservacionAtipico() {
        return this.observacionAtipico;
    }
    
    public void setObservacionAtipico(String observacionAtipico) {
        this.observacionAtipico = observacionAtipico;
    }
    public String getObservacionPrioridad() {
        return this.observacionPrioridad;
    }
    
    public void setObservacionPrioridad(String observacionPrioridad) {
        this.observacionPrioridad = observacionPrioridad;
    }


    public String getNombreContacto() {
        return nombreContacto;
    }

    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }

    public String getCargoContacto() {
        return cargoContacto;
    }

    public void setCargoContacto(String cargoContacto) {
        this.cargoContacto = cargoContacto;
    }

    public String getCorreoContacto() {
        return correoContacto;
    }

    public void setCorreoContacto(String correoContacto) {
        this.correoContacto = correoContacto;
    }

    public String getDireccionCliente() {
        return direccionCliente;
    }

    public void setDireccionCliente(String direccionCliente) {
        this.direccionCliente = direccionCliente;
    }

    public String getCelularTelefono() {
        return celularTelefono;
    }

    public void setCelularTelefono(String celularTelefono) {
        this.celularTelefono = celularTelefono;
    }

    public String getCiudadDepartamento() {
        return ciudadDepartamento;
    }

    public void setCiudadDepartamento(String ciudadDepartamento) {
        this.ciudadDepartamento = ciudadDepartamento;
    }

    public String getNumeroCotizacion() {
        return numeroCotizacion;
    }

    public void setNumeroCotizacion(String numeroCotizacion) {
        this.numeroCotizacion = numeroCotizacion;
    }

    public String getRazonSocial() {
        return razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    public int getTiempoDiaAtipico() {
        return tiempoDiaAtipico;
    }

    public void setTiempoDiaAtipico(int tiempoDiaAtipico) {
        this.tiempoDiaAtipico = tiempoDiaAtipico;
    }

    public int getTiempoHoraAtipico() {
        return tiempoHoraAtipico;
    }

    public void setTiempoHoraAtipico(int tiempoHoraAtipico) {
        this.tiempoHoraAtipico = tiempoHoraAtipico;
    }

    public int getTiempoMinutoAtipico() {
        return tiempoMinutoAtipico;
    }

    public void setTiempoMinutoAtipico(int tiempoMinutoAtipico) {
        this.tiempoMinutoAtipico = tiempoMinutoAtipico;
    }

    public int getTiempoDiaOferta() {
        return tiempoDiaOferta;
    }

    public void setTiempoDiaOferta(int tiempoDiaOferta) {
        this.tiempoDiaOferta = tiempoDiaOferta;
    }

    public int getTiempoHoraOferta() {
        return tiempoHoraOferta;
    }

    public void setTiempoHoraOferta(int tiempoHoraOferta) {
        this.tiempoHoraOferta = tiempoHoraOferta;
    }

    public int getTiempoMinutoOferta() {
        return tiempoMinutoOferta;
    }

    public void setTiempoMinutoOferta(int tiempoMinutoOferta) {
        this.tiempoMinutoOferta = tiempoMinutoOferta;
    }

    public Usuario getIdProfesionalAsignado() {
        return idProfesionalAsignado;
    }

    public void setIdProfesionalAsignado(Usuario idProfesionalAsignado) {
        this.idProfesionalAsignado = idProfesionalAsignado;
    }

    public TipoCertificacion getIdTipoCertificacion() {
        return idTipoCertificacion;
    }

    public void setIdTipoCertificacion(TipoCertificacion idTipoCertificacion) {
        this.idTipoCertificacion = idTipoCertificacion;
    }

    


}


