package sys.model;
// Generated 3/10/2018 12:48:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tiempo generated by hbm2java
 */
public class Tiempo  implements java.io.Serializable {


     private int idTiempo;
     private int dias;
     private int horas;
     private int  minutos;
     private String detalle;
     private Estado idEstado;

    public Tiempo() {
    }

    public Tiempo(int idTiempo, int dias, int horas, int minutos, String detalle, Estado idEstado) {
       this.idTiempo = idTiempo;
       this.dias = dias;
       this.horas = horas;
       this.minutos = minutos;
       this.detalle = detalle;
       this.idEstado = idEstado;
    }
   
    public int getIdTiempo() {
        return this.idTiempo;
    }
    
    public void setIdTiempo(int idTiempo) {
        this.idTiempo = idTiempo;
    }

    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    public int getDias() {
        return dias;
    }

    public void setDias(int dias) {
        this.dias = dias;
    }

    public int getHoras() {
        return horas;
    }

    public void setHoras(int horas) {
        this.horas = horas;
    }

    public int getMinutos() {
        return minutos;
    }

    public void setMinutos(int minutos) {
        this.minutos = minutos;
    }

    public Estado getIdEstado() {
        return idEstado;
    }

    public void setIdEstado(Estado idEstado) {
        this.idEstado = idEstado;
    }




}


